//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocentrale.Apps.Db.LexfindCache
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LexFindCacheContainer : DbContext
    {
        public LexFindCacheContainer()
            : base("name=LexFindCacheContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RechtsnormLF> RechtsnormLFSet { get; set; }
        public DbSet<RechtsnormAusserKraft> RechtsnormAusserKraftSet { get; set; }
    }
}
