//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocentrale.Apps.Db.LexfindCache
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechtsnormLF
    {
        public RechtsnormLF()
        {
            this.RechtsnormAusserKraft = new HashSet<RechtsnormAusserKraft>();
        }
    
        public int Id { get; set; }
        public string Kanton { get; set; }
        public string SysNr { get; set; }
        public Nullable<System.DateTime> Infkrafttreten { get; set; }
        public Nullable<int> LexFindId { get; set; }
        public string LexFindUrl { get; set; }
        public string OrigUrl { get; set; }
        public Nullable<System.DateTime> InKraftSeit { get; set; }
        public string Abk { get; set; }
        public string Titel { get; set; }
        public Nullable<bool> AusserKraft { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> SeenInNewestSync { get; set; }
    
        public virtual ICollection<RechtsnormAusserKraft> RechtsnormAusserKraft { get; set; }
    }
}
