//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocentrale.Apps.Db.LexfindCache
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechtsnormAusserKraft
    {
        public int Id { get; set; }
        public Nullable<int> LexFindId { get; set; }
        public string LexFindUrl { get; set; }
        public Nullable<System.DateTime> InKraftVon { get; set; }
        public Nullable<System.DateTime> InKraftBis { get; set; }
        public Nullable<System.DateTime> FormlosBerichtigtAm { get; set; }
        public int RechtsnormId { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> SeenInNewestSync { get; set; }
    
        public virtual RechtsnormLF Rechtsnorm { get; set; }
    }
}
