//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocentrale.Apps.Db.Law
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikel
    {
        public Artikel()
        {
            this.OerebDefinition = new HashSet<OerebDefinition>();
        }
    
        public string Nr { get; set; }
        public string Text { get; set; }
        public int Id { get; set; }
        public Nullable<bool> IsLive { get; set; }
        public Nullable<System.DateTime> VisibilityDate { get; set; }
        public string Source { get; set; }
        public string OriginalId { get; set; }
    
        public virtual ICollection<OerebDefinition> OerebDefinition { get; set; }
        public virtual Rechtsnorm Rechtsnorm { get; set; }
    }
}
