//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocentrale.Apps.Db.Law
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OerebLaw3Container : DbContext
    {
        public OerebLaw3Container()
            : base("name=OerebLaw3Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OerebDefinition> OerebDefinitionSet { get; set; }
        public DbSet<ZustStelle> ZustStelleSet { get; set; }
        public DbSet<Rechtsstatus> RechtsstatusSet { get; set; }
        public DbSet<OerebKThema> OerebKThemaSet { get; set; }
        public DbSet<ArtCode> ArtCodeSet { get; set; }
        public DbSet<Artikel> ArtikelSet { get; set; }
        public DbSet<Rechtsnorm> RechtsnormSet { get; set; }
        public DbSet<RechtsnormTyp> RechtsnormTypSet { get; set; }
    }
}
