//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geocentrale.Apps.Db.Law
{
    using System;
    using System.Collections.Generic;
    
    public partial class OerebDefinition
    {
        public OerebDefinition()
        {
            this.Rechtsnorm = new HashSet<Rechtsnorm>();
            this.Children = new HashSet<OerebDefinition>();
            this.Artikel = new HashSet<Artikel>();
        }
    
        public int Id { get; set; }
        public string Aussage { get; set; }
        public string UmschreibungRaumbezug { get; set; }
        public string LinkGeobasisdaten { get; set; }
        public string ArtCodeliste { get; set; }
        public Nullable<bool> IsLive { get; set; }
        public Nullable<System.DateTime> VisibilityDate { get; set; }
        public string Source { get; set; }
        public string OriginalId { get; set; }
    
        public virtual ICollection<Rechtsnorm> Rechtsnorm { get; set; }
        public virtual OerebKThema OerebKThema { get; set; }
        public virtual Rechtsstatus Rechtsstatus { get; set; }
        public virtual ArtCode ArtCode { get; set; }
        public virtual OerebDefinition Parent { get; set; }
        public virtual ICollection<OerebDefinition> Children { get; set; }
        public virtual ZustStelle ZustStelle { get; set; }
        public virtual ICollection<Artikel> Artikel { get; set; }
    }
}
